export enum ActionType {
    SIDE_BAR = "SIDE_BAR",
    MAIN = "MAIN",
    MAIN_UPDATE = "MAIN_UPDATE",
    HELP = "HELP",
    CONNECT = "CONNECT",
    DISCONNECT = "DISCONNECT",
    ERROR = "ERROR",
    MAIN_VARIABLES = "MAIN_VARIABLES",
    MAIN_AUTOSTART = "MAIN_AUTOSTART",
    MAIN_ENV = "MAIN_ENV",
    MAIN_KEYBINDS = "MAIN_KEYBINDS"
}

export enum ActionLinks {
    MOUSE_AND_TOUCHPAD = "MOUSE_AND_TOUCHPAD",
    CURSOR = "CURSOR",
    GESTURES = "GESTURES",
    KEYBOARD = "KEYBOARD",
    KEYBINDS = "KEYBINDS",
    DISPLAY_AND_MONITOR = "DISPLAY_AND_MONITOR",
    TOUCH = "TOUCH",
    LAYOUT_GENERAL = "LAYOUT_GENERAL",
    DWINDLE_LAYOUT = "DWINDLE_LAYOUT",
    MASTER_LAYOUT = "MASTER_LAYOUT",
    WORKSPACE_RULES = "WORKSPACE_RULES",
    WINDOW_RULES = "WINDOW_RULES",
    GROUPS = "GROUPS",
    GAPS_AND_BORDERS = "GAPS_AND_BORDERS",
    WINDOW_DECORATION = "WINDOW_DECORATION",
    BLUR = "BLUR",
    SHADOW = "SHADOW",
    ANIMATIONS = "ANIMATIONS",
    ENV = "ENV",
    AUTOSTART = "AUTOSTART",
    MISC = "MISC",
    GRAPHICS = "GRAPHICS",
    ECOSYSTEM = "ECOSYSTEM",
    EXPERIMENT = "EXPERIMENT",
    DEBUG = "DEBUG",
    VARIABLES = "VARIABLES"
}


export enum HyprlandTypes {
    INT = "INT",
    BOOL = "BOOL",
    FLOAT = "FLOAT",
    COLOR = "COLOR",
    VEC2 = "VEC2",
    MOD = "MOD",
    STR = "STR",
    GRADIENT = "GRADIENT",
    FONT_WEIGHT = "FONT_WEIGHT"
}

export enum HyprlandUIType {
    INPUT_INT = "INPUT_INT",
    INPUT_TOGGLE = "INPUT_TOGGLE",
    INPUT_RANGE = "INPUT_RANGE",
    INPUT_STR_SELECT = "INPUT_STR_SELECT",
    INPUT_STR = "INPUT_STR",
    INPUT_FLOAT = "INPUT_FLOAT",
    INPUT_INT_SELECT = "INPUT_INT_SELECT",
    INPUT_VEC = "INPUT_VEC",
    INPUT_COLOR = "INPUT_COLOR",
    INPUT_GRADIANT = "INPUT_GRADIANT"
}

export enum MainPageActionStatus {
    SUCCESS = "SUCCESS",
    ERROR = "ERROR",
}