[versions]
logback-version = "1.5.18"
kotlin-version = "2.1.20"
ktor-version = "3.1.1"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-version" }

[plugins]
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }